version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: aact_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5236
      POSTGRES_DB: aact
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: